<a href="https://colab.research.google.com/github/git07Sandesh/Pytorch-Practice/blob/main/PyTorch_beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#Introduction to Tensor

In [ ]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


###Random Tensors

## ok so most of the tensors in deep learning starts with random tensors and then updates the values of tensor by learning

In [ ]:
random_tensor = torch.rand(1,3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.4028, 0.0164, 0.3961, 0.7714],
         [0.7022, 0.5326, 0.2703, 0.6371],
         [0.7321, 0.5491, 0.0345, 0.9226]]])
3
torch.Size([1, 3, 4])


In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)
#

tensor([[[8.8891e-01, 1.0470e-01, 8.2391e-01,  ..., 4.5715e-01,
          2.4034e-01, 9.9313e-01],
         [5.6722e-01, 4.5726e-01, 6.7427e-01,  ..., 3.4497e-01,
          9.8690e-01, 6.0996e-01],
         [1.4420e-01, 4.0446e-02, 5.3764e-01,  ..., 5.3617e-01,
          3.7611e-02, 9.9418e-01],
         ...,
         [2.3340e-01, 7.8338e-01, 9.1727e-02,  ..., 7.3704e-01,
          1.5583e-01, 1.1155e-01],
         [3.0879e-01, 7.2315e-01, 4.0507e-01,  ..., 8.6535e-01,
          1.3020e-01, 6.4096e-01],
         [1.3017e-01, 1.8663e-01, 3.3404e-01,  ..., 7.4260e-01,
          2.6448e-01, 6.6709e-01]],

        [[3.6459e-01, 1.0082e-03, 8.9396e-01,  ..., 6.5259e-01,
          4.0694e-01, 8.5343e-01],
         [4.2255e-01, 7.6811e-01, 2.3216e-01,  ..., 1.6233e-01,
          9.1410e-01, 2.7679e-01],
         [6.0348e-01, 6.4326e-01, 6.4171e-01,  ..., 5.0187e-01,
          3.6922e-01, 2.4633e-01],
         ...,
         [9.2379e-01, 5.8638e-01, 1.5103e-01,  ..., 8.4192e-01,
          6.628

# ZEROS AND ONES

In [ ]:
zeros = torch.zeros(size=(3,4))
print(zeros)
print(zeros.ndim)
print(zeros.shape)
ones = torch.ones(size=(3,4))
print(ones)
print(ones.ndim)
print(ones.shape)
# Default data type is float

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.Size([3, 4])


### CREATING a RANGE of TENSOR

In [ ]:
odd_num = torch.arange(1,15,2)


In [ ]:
#Create tensors-like
ten_zeros = torch.zeros_like(input=odd_num)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0])


## Tensor DataType

In [ ]:
#Device type is set to CPU as default

float32_tensor = torch.tensor((1,2,3,4,5), dtype=torch.float32, device=None, requires_grad=False)
float32_tensor
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor
int32_tensor = torch.tensor((1,2,3,4,5), dtype=torch.int32, device=None, requires_grad=False)
int32_tensor




tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [ ]:
div = float16_tensor / float32_tensor
div.dtype
mult = float16_tensor * int32_tensor
mult.dtype


torch.float16

#Tensor Manipulation:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
new_tensor = torch.rand(5)
print(new_tensor + 10)
print(new_tensor * 10)
print(new_tensor - 10)
print(new_tensor / 10)
print(new_tensor * new_tensor)

tensor([10.4038, 10.0442, 10.7627, 10.8089, 10.2593])
tensor([4.0383, 0.4418, 7.6272, 8.0893, 2.5925])
tensor([-9.5962, -9.9558, -9.2373, -9.1911, -9.7407])
tensor([0.0404, 0.0044, 0.0763, 0.0809, 0.0259])
tensor([0.1631, 0.0020, 0.5817, 0.6544, 0.0672])


#Matrix Multiplication:
Multiply two matrices of the same order.
1. Element-wise Multiplication (Scalar Product)
2. Matrix Multiplication (Dot Product)

In [ ]:
# Element-wise Multiplication: Each element is multiplied by its adjacent element
common_tensor = torch.tensor([[1,2,3,4,5],[2,3,4,5,6]])
print(common_tensor * common_tensor)
## You can see how the result will be (Aij)^2: MEaning each element in an index is multiplied by same element.

tensor([[ 1,  4,  9, 16, 25],
        [ 4,  9, 16, 25, 36]])


In [ ]:
%%time
MATRIX1 = torch.tensor([[1,2],[2,3]])
MATRIX2 = torch.tensor([[1,2],[2,3]])
MAT_mult = torch.matmul(MATRIX1,MATRIX2)
print(MAT_mult)
# The result is a new n*m matrix resulted by a dot product.



tensor([[ 5,  8],
        [ 8, 13]])
CPU times: user 819 µs, sys: 123 µs, total: 942 µs
Wall time: 7.71 ms


### How to deal with shape error:
1. Transpose the matrix: switches the axes or dimension of the given tensor (remember that the data is still the same but just its axes have been changed. Might affect is the axes represent something specific)


In [ ]:
A = torch.rand(3,4);
B = torch.rand(3,4);
print(A)
print(B)
# HEre A & B cannot be multiplied because the outer dimension of first is not same as second. So we transpose the second.
B_T = B.T
print(B_T)
print(torch.matmul(A,B_T))

tensor([[0.4971, 0.8190, 0.5038, 0.0225],
        [0.1992, 0.3566, 0.8806, 0.5070],
        [0.6553, 0.4151, 0.6243, 0.3868]])
tensor([[0.7510, 0.1204, 0.0731, 0.8892],
        [0.3799, 0.7797, 0.3308, 0.7230],
        [0.1010, 0.7524, 0.9642, 0.4941]])
tensor([[0.7510, 0.3799, 0.1010],
        [0.1204, 0.7797, 0.7524],
        [0.0731, 0.3308, 0.9642],
        [0.8892, 0.7230, 0.4941]])
tensor([[0.5288, 1.0104, 1.1633],
        [0.7077, 1.0115, 1.3879],
        [0.9316, 1.0588, 1.1716]])


# Other operations: MAX, MIN, SUM, MEAN, etc: TENSOR AGGREDATION

In [ ]:
X = torch.arange(1, 100, 10)
print(X)
print(X.min(),',', torch.min(X))
print(X.max(), torch.max(X))
print(X.type(torch.float32).mean(), torch.mean(X.type(torch.float32)))
print(X.sum(), torch.sum(X))



tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1) , tensor(1)
tensor(91) tensor(91)
tensor(46.) tensor(46.)
tensor(460) tensor(460)


### Now we will discuss about the positional min and max:


In [ ]:
print(X.argmin())
print(X.argmax())
print(X.argwhere())

tensor(0)
tensor(9)
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


### NOw we will take a step further and perform complex operations on Tensors:
1. Reshaping: Changing the shape of tensors to match the desired shape
2. Stacking: Combining the tensors on top of each other (vertical or horizontal)
3. Squeezing: removes all `1` dimensions from a tensor
4. Unsqueezing: adds a `1` dimension to the tensor
5. Permute: Returns a view with dimensions swapped in certain ways
6. View: Return a view of an input tensor keeping the memory constant. (It returns the original tensor so any change in view will affect the original tensor) (It's alternate is copy which creates a new space in the memory).


In [ ]:
import torch
A = torch.arange(1,100, 10)
print(A.shape)
print(A.reshape(2,5))

torch.Size([10])
tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])


In [ ]:
z = A.view(1,10)
print(z, A)
#Notice how changing the view changed the original tensor as well which had a different size.


tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]) tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


In [ ]:
#Stacking tensors on top of each other.
B = torch.tensor([[1],[2],[3],[4],[5],[6
                                      ],[7],[8],[9],[10]])
tensor_1stack = torch.hstack([A,A])
tensor_2stack = torch.hstack([B,B])
print(tensor_1stack)
print(tensor_2stack)
#

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91,  1, 11, 21, 31, 41, 51, 61, 71,
        81, 91])
tensor([[ 1,  1],
        [ 2,  2],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10]])


In [ ]:
x = torch.zeros(2,1,2,1,1)
x.size()
y = x.squeeze(0) # This is a copy.
z = x.squeeze(1) # This is a copy.
a = x.squeeze(2) # This is a copy.
b = x.squeeze(3) # This is a copy.
c = x.squeeze(4) # This is a copy.
print(x.size())
print(y.size())
print(z.size())
print(a.size())
print(b.size())
print(c.size())



torch.Size([2, 1, 2, 1, 1])
torch.Size([2, 1, 2, 1, 1])
torch.Size([2, 2, 1, 1])
torch.Size([2, 1, 2, 1, 1])
torch.Size([2, 1, 2, 1])
torch.Size([2, 1, 2, 1])


In [ ]:
a_un = a.unsqueeze(0)
print(a.size())
print(a_un.size())

torch.Size([2, 1, 2, 1, 1])
torch.Size([1, 2, 1, 2, 1, 1])


In [ ]:
#THis is how we use permute:

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,1,0)
print(x_original.shape)
print(x_permuted.shape)
# THis is a view


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


### INDEXING: SIMILAR AS NUMPY

In [ ]:
import torch
x = torch.arange(1, 10).reshape((1,3,3))
x





tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#This is basic direct indexing.

print(x[0])
print(x[0][0])
print(x[0][2])
print(x[0][0][0])
print(x[0][1][1])
print(x[0][2][2])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([7, 8, 9])
tensor(1)
tensor(5)
tensor(9)


In [ ]:
#Now we will modify it slightly.  Try to slice the arrays
print(x[:, :, 2])
for i in range(3):
  print(x[:,i,2-i])


tensor([[3, 6, 9]])
tensor([3])
tensor([5])
tensor([7])


### Numpy and Tensor
We can convert numpy array to tensor and tensor to numpy:
1. Numpy Array -> Pytorch Tensor: torch.torch.from_numpy(ndarray)
2. Pytorch Tensor -> Numpy Array: torch.Tensor.numpy()

In [ ]:
#Be careful numpy uses float 64 and tensor default is float32 but it takes 64 when changing from numpy to tensor.

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor)

In [ ]:
#Tensor to Numpy:

tensor = torch.ones(2,3)
numpy = tensor.numpy()
print(tensor.dtype)
print(numpy.dtype)

torch.float32
float32


In [ ]:
!nvidia-smi


Thu Jun  5 03:56:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### OK NOW we will be using PYTORCH WORFLOWS: